name: publish-docs

on:
  push:
    branches:
      - '**'
      - '!gh-pages'
  pull_request:
    branches:
      - 'main'

env:
  node-version: 14.x
  python-version: 3.x

jobs:
  build:
      - name: Run shellcheck
        uses: reviewdog/action-shellcheck@v1.13.0
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          path: |
            bin
            .husky
          pattern: '*.sh'
          check_all_files_with_shebangs: 'true'

      - name: Prepare docs
        run: make prepare

      - name: Build docs
        run: mkdocs build

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2# renovate: tag=v2.3.1
        with:
          name: site
          path: site
          if-no-files-found: error

      - name: Publish docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
